#!/bin/bash
BUILD_PATH=$(echo ${DOCKERFILE_PATH}| sed 's#/#..#g' | sed 's#[a-zA-Z0-9]\+#/#g' | cut -c 2- )
 
docker build --target=bookworm -f $(basename ${DOCKERFILE_PATH}) -t $DOCKER_REPO:latest -t $DOCKER_REPO:steam -t $DOCKER_REPO:steam-bookworm ${BUILD_PATH}.
docker build --target=bookworm-root -f $(basename ${DOCKERFILE_PATH}) -t $DOCKER_REPO:root -t $DOCKER_REPO:root-bookworm ${BUILD_PATH}.
