---
name: Developer image
on:  # yamllint disable-line rule:truthy
  push:
    branches: [master]

jobs:
  push:
    runs-on: ARM64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: type=raw,value=dev
          flavor: latest=false

      - name: Docker - Build / Push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          target: bullseye
          push: true
          tags: ${{ steps.meta.outputs.tags }}
  push-root:
    runs-on: ARM64
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker - Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ github.repository }}
          tags: type=raw,value=dev-root
          flavor: latest=false

      - name: Docker - Build / Push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          target: bullseye-root
          push: true
          tags: ${{ steps.meta.outputs.tags }}
