---
name: Linting
on:  # yamllint disable-line rule:truthy
  pull_request:

run-name: Pull request - ${{ github.event.pull_request.number }}
jobs:
  shellcheck:
    name: Lint - Shell
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@2.0.0

  dockerlint:
    strategy:
      matrix:
        debian-version:
          - bookworm
          - bullseye
    name: Lint - Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.debian-version }}/Dockerfile

  test-build:
    strategy:
      matrix:
        debian-version:
          - bookworm
          - bullseye
    name: Docker - Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker - Build
        uses: docker/build-push-action@v5
        with:
          push: false
          platforms: linux/arm64
          file: ${{ matrix.debian-version }}/Dockerfile
          target: ${{ matrix.debian-version }}
